skip_non_tags: true

image: Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.13.2\msvc2017_64
  - set PATH=%QTDIR%\bin;\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%;
build_script:
  # get libtorch
  - curl https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.4.0.zip -o libtorch-win-shared-with-deps-1.4.0.zip
  - ps: Expand-Archive -Force libtorch-win-shared-with-deps-1.4.0.zip app/lib/
  # setup build env
  - vcvars64.bat
  #- set QMAKESPEC=win32-msvc
  # build app
  - qmake -config release -r eNoseAnnotator.pro
  - nmake
  - cd "app/release/"
  - ren app.exe eNoseAnnotator.exe
  - cd ../..
after_build:
  # create executable
  - cd app
  - windeployqt --compiler-runtime release/eNoseAnnotator.exe
  # remove unneeded files
  - rm release/*.obj
  - rm release/*.cpp
  - rm release/*.h
  # create directories to be deployed
  - cd ..
  - if "%APPVEYOR_REPO_TAG_NAME%" equ "continuous" set NAME=continuous else set NAME=APPVEYOR_REPO_TAG_NAME
  - mkdir "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/data/" "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/export/" "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/presets/" "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/classifiers/"
  - cp app/lib/libtorch/lib/*.dll "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/"
  - cp -r app/release/* "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/"
  - cp -r misc/presets "eNoseAnnotator-%NAME%-Windows/eNoseAnnotator-%NAME%-Windows/"

artifacts:


  - path: eNoseAnnotator-continuous-Windows
    type: zip
  - path: "eNoseAnnotator-${APPVEYOR_REPO_TAG_NAME}-Windows"
    type: zip

deploy:
  - provider: GitHub
    name: continuous
    on:
       APPVEYOR_REPO_TAG: false
    artifact: eNoseAnnotator-continuous-Windows.zip
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: vgEATF2g25z4SRuiZeER1PiOcABqDjPdOilt5Yb0irKOVbhT14kQcPVNQ5UEbQ75

  - provider: GitHub
    name: release
    on:
       APPVEYOR_REPO_TAG: true
    artifact: "eNoseAnnotator-${APPVEYOR_REPO_TAG_NAME}-Windows.zip"
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: vgEATF2g25z4SRuiZeER1PiOcABqDjPdOilt5Yb0irKOVbhT14kQcPVNQ5UEbQ75	
