skip_non_tags: true

image: Visual Studio 2015
install:
  - set QTDIR=C:\Qt\5.13.2\mingw73_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_32\bin;%PATH%;
build_script:
  - qmake eNoseAnnotator.pro
  - mingw32-make
  - cd "app/release/"
  - ren app.exe eNoseAnnotator.exe
  - cd ../..
after_build:
  - cd app
  - windeployqt release/eNoseAnnotator.exe
  - rm release/*.o
  - rm release/*.cpp
  - cd ..
  - echo %appveyor_build_version%
  - mkdir eNoseAnnotator-Windows
  - mkdir "eNoseAnnotator-Windows/eNoseAnnotator/"
  - cp -r app/release/* "eNoseAnnotator-Windows/eNoseAnnotator/"

artifacts:
  - path: eNoseAnnotator-Windows
    type: zip

deploy:
  - provider: GitHub
    name: production
    artifact: eNoseAnnotator-Windows.zip
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: vgEATF2g25z4SRuiZeER1PiOcABqDjPdOilt5Yb0irKOVbhT14kQcPVNQ5UEbQ75
    on:
      APPVEYOR_REPO_TAG: true

