branches:
  only:
    - master

image: Visual Studio 2015
install:
  - set QTDIR=C:\Qt\5.13.2\mingw73_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake eNoseAnnotator.pro
  - mingw32-make
  - cd
  - dir app/release/usr/bin
  - ren "app/release/usr/bin/app.exe" eNoseAnnotator.exe
after_build:
  - windeployqt app/release/usr/bin/eNoseAnnotator.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\eNoseAnnotator-*.exe
  - path: release
    type: zip
