language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    before_install:
      - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
      - sudo apt-get update -qq
    install:
      - sudo apt-get -y install qt510base  qt510serialport libgl1-mesa-dev tree
      - source /opt/qt*/bin/qt*-env.sh
    compiler:
      - gcc
    script:
      - qmake CONFIG+=release PREFIX=/usr
      - make -j$(nproc)
      - make INSTALL_ROOT=eNoseAnnotator -j$(nproc) install ; find eNoseAnnotator/
      - mkdir -p eNoseAnnotator/usr/bin; mkdir -p eNoseAnnotator/share/icons/hicolor/256x256; cp app/app eNoseAnnotator/usr/bin/app; cp misc/icon.png eNoseAnnotator/share/icons/hicolor/256x256/icon.png;
      - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      # export VERSION=... # linuxdeployqt uses this for naming the file
      - ./linuxdeployqt-continuous-x86_64.AppImage eNoseAnnotator/usr/share/applications/*.desktop -appimage 
    
    after_success:
      # find eNoseAnnotator -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
      # curl --upload-file eNoseAnnotator*.AppImage https://transfer.sh/eNoseAnnotator-git.$(git rev-parse --short HEAD)-x86_64.AppImage
      - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      - bash upload.sh eNoseAnnotator*.AppImage*

  - os: windows
    before_install:
    - dir C:/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.17134.0/x64
    - cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd && cd "C:\Users\travis\build\Tilagiho\eNoseAnnotator" && dir'
    - curl -vLO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
    - curl -vLO https://raw.githubusercontent.com/appveyor/build-images/0d76961abbd8208c709baa89aa1cfbb5778bd17c/scripts/Windows/qt-installer-windows.qs
    install:
    - "./qt-unified-windows-x86-online.exe --verbose --script qt-installer-windows.qs"
    - ls -la C:/Qt/5.12.3/msvc2017/bin/qtenv2.bat
    script:
    - cmd.exe /C 'cd && "C:\Qt\5.12.3\msvc2017\bin\qtenv2.bat" && cd && "C:\Program
      Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd "C:\Users\travis\build\" && cd && qmake eNoseAnnotator.pro
      && nmake'

  
# safelist
branches:
  only:
  - master
  - stable

