language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
        - sourceline: "ppa:ubuntu-toolchain-r/test"
        packages:
          - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
      # use g++-7
      - eval "${MATRIX_EVAL}"
      - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
      - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
      # qt version needed for linuxdeployqt
      - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
      - sudo apt-get update -qq
    install:
      # qt version needed for linuxdeployqt
      - sudo apt-get -y install qt510base  qt510serialport  qt510svg libgl1-mesa-dev tree
      - source /opt/qt*/bin/qt*-env.sh  
      # pytorch
      - wget -c -nv https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip
      - unzip -q -o libtorch-*.zip  -d app/lib/
      # qwt
      - bash -xv scripts/install_qwt.sh
      # linux-syscall-support for google breakpad
      - git clone https://chromium.googlesource.com/linux-syscall-support app/lib/QCrashHandler/deps/breakpad.git/src/third_party/lss
    compiler:
      - gcc-7
    script:
      # build AppImage & create directory structure
      - bash -xv scripts/build.sh
    
    after_success:
      - ls
      - bash -xv scripts/upload.sh 

# safelist
branches:
  only:
  - master
  - stable
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
