language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: "ppa:ubuntu-toolchain-r/test"
        packages:
          - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
      # use g++-7
      - eval "${MATRIX_EVAL}"
      - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
      - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
      # add repo for qt 13.2
      - sudo add-apt-repository ppa:beineri/opt-qt-5.13.2-xenial -y
      - sudo apt-get update -qq
    install:
      # qt version needed for linuxdeployqt
      - sudo apt-get -y install  qt513base  qt513serialport libgl1-mesa-dev tree
      - source /opt/qt*/bin/qt*-env.sh   
      # get libtorch
      - wget -c -nv https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.4.0%2Bcpu.zip
      - unzip -q -o libtorch-*.zip  -d app/lib/
      # add linux syscall support needed for QCrashHandler
      - git clone https://chromium.googlesource.com/linux-syscall-support app/lib/QCrashHandler/deps/breakpad.git/src/third_party/lss
    compiler:
      - gcc-7
    script:
      # build AppImage & create directory structure
      - bash -xv scripts/build.sh
    
    after_success:
      # find eNoseAnnotator -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
      # curl --upload-file eNoseAnnotator*.AppImage https://transfer.sh/eNoseAnnotator-git.$(git rev-parse --short HEAD)-x86_64.AppImage
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh; fi'
      # upload continuous pre-release
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ]; then bash upload.sh eNoseAnnotator-continuous-linux.zip "symbols_${TRAVIS_COMMIT}_linux.zip"; fi'
      # upload release
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ]; then UPLOADTOOL_SUFFIX="${TRAVIS_TAG}"; bash upload.sh "eNoseAnnotator-${TRAVIS_TAG}-linux.zip" "symbols_${TRAVIS_COMMIT}_linux.zip"; fi'
      
      # upload debug symbols

# safelist
branches:
  only:
  - master
  - stable
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

