language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
      # use g++-7
      - eval "${MATRIX_EVAL}"
      - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
      - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
      # qt version needed for linuxdeployqt
      - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
      - sudo apt-get update -qq
    install:
      # qt version needed for linuxdeployqt
      - sudo apt-get -y install qt510base  qt510serialport libgl1-mesa-dev tree
      - source /opt/qt*/bin/qt*-env.sh   
      # get libtorch
      - wget -c -nv https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.4.0%2Bcpu.zip
      - unzip -q -o libtorch-*.zip  -d app/lib/
    compiler:
      - gcc-7
    script:
      # build AppImage & create directory structure
      - ./build/build.sh
    
    after_success:
      # find eNoseAnnotator -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
      # curl --upload-file eNoseAnnotator*.AppImage https://transfer.sh/eNoseAnnotator-git.$(git rev-parse --short HEAD)-x86_64.AppImage
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh; fi'
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash upload.sh eNoseAnnotator-continuous-linux.zip; fi'

# safelist
branches:
  only:
  - master
  - stable

