name: windows-build
on: [push]
jobs:
  build-app:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: Qt
          key: ${{ runner.os }}-QtCache_v2
          
      - name: Cache Qwt
        uses: actions/cache@v2
        id: cache-qwt
        with:
          path: C:/Qwt-6.1.5
          key: ${{ runner.os }}-Qwt-Cache
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.13.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2017_64'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          modules: 'qtserialport qtsvg qtopengl'
          setup-python: 'true'
          tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
          # set-env: 'false'
          tools-only: 'false'
          aqtversion: '==1.1.3'
          py7zrversion: '==0.14.0'
          extra: '--external 7z'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          
      #                     #
      #     prepare build   #
      #                     #
      - name: setup build env
        run: echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\\" >> $GITHUB_PATH
        shell: bash

      - name: get libtorch
        run: |
             $client = new-object System.Net.WebClient
             $client.DownloadFile("https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.6.0%2Bcpu.zip","libtorch.zip")
      - name: extract libtorch
        run: |
          7z t libtorch.zip
          7z x libtorch.zip -oapp/lib/
        shell: cmd
        
      - name: get fetch
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://github.com/gruntwork-io/fetch/releases/download/v0.4.2/fetch_windows_386.exe","fetch.exe")
        
      - name: get eNoseUploader
        run: |
          fetch.exe --repo="https://github.com/SmartNanotubes-Technologies/eNoseUploader" --tag="v1.0" --release-asset="eNoseUploader_Windows.zip" .
        env: 
          GITHUB_OAUTH_TOKEN: ${{ secrets.ACCESS_TOKEN  }}
        shell: cmd

      # install qwt
      - name: Install Qwt
        if: steps.cache-qwt.outputs.cache-hit != 'true'
        run: .\scripts\install_qwt.ps1

      #                     #
      #     build app       #
      #                     #
      - name: build app
        run: .\scripts\build.ps1

      #                             #
      #     create executable       #
      #                             #
      - name: create executable
        run: |
          cd app
          windeployqt --verbose 2 --compiler-runtime release/eNoseAnnotator.exe
        shell: cmd
                
      - name: remove unnecessary files
        run: |
          cd app
          rm release/*.obj
          rm release/*.cpp
          rm release/*.h
          dir release
        shell: cmd

      - name: create directories to be deployed
        run: |
         PREFIX=${GITHUB_REF##*/}
         if [[ ${PREFIX} == "v*" ]]
         then
           SUFFIX="-continuous"
         fi
         DEPLOY_DIR="eNoseAnnotator-${PREFIX}${SUFFIX}-Windows"
         echo "DEPLOY_NAME=${PREFIX}${SUFFIX}" >> ${GITHUB_ENV}
         echo "DEPLOY_DIR=${DEPLOY_DIR}" >> ${GITHUB_ENV}
         
         mkdir -p "${DEPLOY_DIR}/${DEPLOY_DIR}/data/" "${DEPLOY_DIR}/${DEPLOY_DIR}/export/" "${DEPLOY_DIR}/${DEPLOY_DIR}/share/presets/" "${DEPLOY_DIR}/${DEPLOY_DIR}/classifiers/" "${DEPLOY_DIR}/${DEPLOY_DIR}/bin/"
         cp -r usr/share/presets "${DEPLOY_DIR}/${DEPLOY_DIR}/share/"
         cp app/lib/libtorch/lib/*.dll app/release
         cp C:/Qwt-6.1.5/lib/*.dll app/release
         cp "${Qt5_Dir}\bin\Qt5OpenGL.dll" app/release
         cp -r app/release/* "${DEPLOY_DIR}/${DEPLOY_DIR}/bin/"
        shell: bash
          
      - name: Decompress eNoseUploader into release dir
        run: |
         7z t eNoseUploader_Windows.zip
         7z x eNoseUploader_Windows.zip -o"%DEPLOY_DIR%/%DEPLOY_DIR%/bin
        shell: cmd
        
      #                             #
      #     generate symbol file    #
      #                             #
      - name: setup environment
        run: |
          cd app
          mv "release\eNoseAnnotator.exe" "app.exe"
          crashHandlerPath="D:\a/eNoseAnnotator/eNoseAnnotator/app/lib/QCrashHandler"
          
          echo "SYMBOL_DIR=${DEPLOY_DIR}/${DEPLOY_DIR}/symbols_${GITHUB_SHA}_win" >> ${GITHUB_ENV}
          echo "SYMBOL_FILE=app.sym" >> ${GITHUB_ENV}
          echo "${crashHandlerPath}/deps/breakpad.git/src/tools/windows/binaries" >> ${GITHUB_PATH}
          echo "${crashHandlerPath}/deps/breakpad.git/src/processor" >> ${GITHUB_PATH}
          echo "-"
        shell: bash
                  
      - name: dump symbols
        run: |          
          cp "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\DIA SDK\bin\msdia140.dll" "C:\Program Files\Common Files\Microsoft Shared\VC\msdia140.dll"
          C:\Windows\system32\regsvr32 /s "C:\Program Files\Common Files\Microsoft Shared\VC\msdia140.dll"

          mkdir "%SYMBOL_DIR%"
          dump_syms "app/release/app.pdb" > "%SYMBOL_DIR%/%SYMBOL_FILE%"
          cp "app/release/app.pdb" "%SYMBOL_DIR%/"
        shell: cmd
        
      - name: load vc_redist
        run: |
             $client = new-object System.Net.WebClient
             $client.DownloadFile("https://aka.ms/vs/16/release/vc_redist.x64.exe","vc_redist.x64.exe")
             Copy-Item "vc_redist.x64.exe" -Destination "$($env:DEPLOY_DIR)/$($env:DEPLOY_DIR)/bin"

      #                         #
      #         deploy          #
      #                         #
      - name: Archive deployment directories
        run: |
          $Env:DEPLOY_ZIP = "$($env:DEPLOY_DIR).zip";
          echo "DEPLOY_ZIP=$Env:DEPLOY_ZIP" >> $Env:GITHUB_ENV;
          Compress-Archive -Path $env:DEPLOY_DIR\* -DestinationPath $Env:DEPLOY_ZIP;
          
      - name: update tag to current commit
        run: |
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag -f ${DEPLOY_NAME}
            git push -f origin ${DEPLOY_NAME}
          fi
        shell: bash    
          
      - name: Create Release        
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: "${{ env.DEPLOY_ZIP }}"
          draft: 'true'
          allowUpdates: 'true'
          artifactErrorsFailBuild: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create Release
        if: startsWith(github.ref, 'refs/heads/')
        uses: ncipollo/release-action@v1.8.6
        with:
          tag: "${{ env.DEPLOY_NAME }}"
          artifacts: "${{ env.DEPLOY_ZIP }}"
          prerelease: 'true'
          allowUpdates: 'true'
          artifactErrorsFailBuild: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

